### PR TITLE
feat: add support for custom LanguageTool command

### LINKED ISSUE #20: Allow using `languagetool` system command instead of `languagetool-server.jar`
Hello!

Can you please provide something like this [flymake-languagetool.el#L80-L84](https://github.com/emacs-languagetool/flymake-languagetool/blob/857f4f94a7615d7de5305a40045b2b85ae1ff760/flymake-languagetool.el#L80-L84)?

In [`flymake-languagetool`](https://github.com/emacs-languagetool/flymake-languagetool), there is an option to use a custom LanguageTool command instead of `languagetool-server.jar`, this is extremely useful for distributions which provide LanguageTool packages (like Arch Linux).

See https://github.com/emacs-languagetool/flymake-languagetool/issues/6 for reference.

Thank you !

### PR DESCRIPTION
**Pull request by abougouffa**
Usage example:

```emacs-lisp
(use-package! flycheck-languagetool
  :ensure t
  :hook (text-mode . flycheck-languagetool-setup)
  :init
  ;; In Arch Linux, `languagetool --http` launches LT in HTTP server mode
  (setq flycheck-languagetool-server-command '("languagetool" "--http")
        flycheck-languagetool-language "auto"))
```

Fixes: #20
Ref: https://github.com/emacs-languagetool/flymake-languagetool/issues/6

### CODE REVIEW

**Comment by jcs090218** [comment]
Looks good to me. @mavit WDYT?

**Comment by mavit** [comment]
Seems fine to me, but I wonder if we can do even better.  If system `languagetool` commands exist, then we should probably try to auto-detect them so that the user doesn't have to do any unnecessary manual configurating.

@abougouffa Is this something you'd be interested in writing a patch to do?

**Comment by abougouffa** [comment]
@mavit I would like to, but I don't think it is a good idea, the command `languagetool` is not an official LanguageTool command, but rather a distro-specific script. 

In Arch Linux, it is implemented as [a pretty simple bash script](https://github.com/archlinux/svntogit-community/blob/packages/languagetool/trunk/languagetool.sh) which exposes the `org.languagetool.server.HTTPServer` class via the `--http` option. 

I've just tested the Ubuntu's `languagetool` command, [packaged as a snap](https://snapcraft.io/install/languagetool/ubuntu), but I didn't find any CLI documentation about it. Other distros might implement the CLI differently, so I prefer leaving this to be configured by the user.

**Comment by mavit** [comment]
Thanks, @abougouffa.

**Pull request merged**
